config/routes.rb
Rails.application.routes.draw do

  root "categories#index"

  resources :categories do
    resources :products, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @products = Product.new
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Categoria creada' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Categoria actualizada' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Categoria eliminada' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def create
     @product = Product.create(products_params)
     @product.category = Category.find(params[:category_id])
     @product.save

     redirect_to @product.category, notice: "Producto creado satisfactoriamente"
   end

   def destroy
     @product = Product.find(params[:id])
     @category = @product.category
     @product.destroy
     redirect_to @category, alert: 'producto eliminado'
   end

  private
 def products_params
   params.require(:product).permit(:name, :price)
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :category_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="container bg-success">
  <h1>Editar categoria</h1>

  <%= render 'form', category: @category %>

  <%= link_to 'Ver', @category %> |
  <%= link_to 'Salir', categories_path %>
</div>

app/views/categories/index.html.erb
<div class="container wrap-main">
  <p id="notice"><%= notice %></p>


  <h1 class="title">Categorias</h1>

  <table class="table table-bordered table-info">
    <thead>
      <tr>
        <th>Nombre</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td class="align-middle"><%= link_to category.name, category %> </td>
          <td class="align-middle text-center"><%= category.products.count %></td>
          <td class="text-center"><%= link_to 'Editar', edit_category_path(category), :class => 'btn btn-success' %></td>
          <td class="text-center"><%= link_to 'Eliminar', category, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-success'%></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Nueva Categoría', new_category_path, class: 'btn btn-info' %>

</div>

app/views/categories/new.html.erb
<div class="container bg-success">
  <h1>Nueva categoria</h1>

  <%= render 'form', category: @category %>

  <%= link_to 'Salir', categories_path %>
</div>

app/views/categories/show.html.erb
<div class="container wrap-main">

  <div class="mb-5">
    <div class="col">
      <p id="notice"><%= notice %></p>
      <p class="info-cat">
        <strong>Nombre:</strong>
        <span><%= @category.name %></span>
      </p>
      <%= link_to 'Editar', edit_category_path(@category), :class => 'btn btn-success' %>
      <%= link_to 'Volver', categories_path, :class => 'btn btn-success' %>
    </div>

    <div class="p-0">

      <h1 class="title">Crear un producto</h1>
      <div class="p-0">
        <%= form_with(model: [ @category, @products ]) do |form| %>
        <div class="form-group">
        <%= form.label :name, "Nombre" %>
        <%= form.text_field :name, :class => "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :price, "Precio" %>
          <%= form.text_field :price, :class => "form-control" %>
        </div>

        <%= form.submit "Guardar", :class => "btn btn-success" %>
        <% end %>

      </div>
    </div>
  </div>


<div class="row mb-5">
  <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope= "col"> Nombre</th>
          <th scope= "col"> Precio</th>
          <th scope= "col"> Opciones</th>
        </tr>
      </thead>
      <tbody>
        <% @category.products.each do |f| %>
        <tr>
          <td class="align-middle"><%= f.name %></td>
          <td class="align-middle"><%= f.price %></td>
          <td> <%= link_to "eliminar", category_product_path(@category, f), method: :delete, :class => 'btn btn-success'%></td>
        </tr>

        <% end %>
      </tbody>
  </table>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <%= link_to 'Crud Anidado', root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Inicio', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Nueva categoría', new_category_path, class: 'nav-link' %>
      </li>
    </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudAnidado</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
</html>